schema_version: 1

context:
  name: swapper
  version: "1.5.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/${{ name[0] }}/${{ name }}/swapper-${{ version }}.tar.gz
  sha256: 405f934265aa0c8d8b8e6b1be584875d1a3b7de6b1cd6f47367a4dbdc028609a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools-scm
    - setuptools
  run:
    - python >=${{ python_min }}
    # Fails import test if not included
    - django >=4.2

tests:
  - python:
      imports:
        - swapper
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - files:
      source:
        - tests
    requirements:
      run:
        - pytest
        - python ${{ python_min }}.*
    script:
      - pytest -vvv --capture=tee-sys tests

about:
  summary: The unofficial Django swappable models API
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/openwisp/django-swappable-models

extra:
  recipe-maintainers:
    - thewchan
